Add a missing export to a TS interface
I have a library with something like:

```ts
import AntSelect from "antd/lib/select";

export const Select = AntSelect;
```

when I run `tsc --emitDeclarationOnly` there's an error:

```
src/index.ts:3:14 - error TS4023: Exported variable 'Select' has or is using name 'SelectInterface' from external module "/Users/elad.ossadon/dev/tmp2/antd-ts-err/node_modules/antd/lib/select/index" but cannot be named.

3 export const Select = AntSelect;
               ~~~~~~
```

Adding this `export` solves it.